### PR TITLE
Integrate 1.0.2.1’s changelog/script changes.

### PR DESCRIPTION
**Pull request by patrickt**
This is just a merge of the `ghc-8.10` branch.

- [ ] Blocked on the release of the candidate in #376.

### CODE REVIEW

**Comment by joshvera** [comment]
Published to https://hackage.haskell.org/package/fused-effects-1.0.2.1.

**Comment by evanrelf** [comment]
Hey @joshvera, was the intent to release the new GADT syntax on Hackage? It looks like 1.0.2.0 didn't have it, and 1.0.2.1 does have it, but I'd consider that a backwards-incompatible, breaking change.

It also looks like the changelog file wasn't updated with a new heading, so this might have been a mistake?

**Comment by joshvera** [comment]
@evanrelf Oh no, you're right! I'll cut a major release and update the changelog.

**Comment by robrix** [comment]
@evanrelf we’ve deprecated the 1.0.2.1 release in hackage, and are gonna ship a 1.0.2.2 rebased off 1.0.2.0 instead of `master`.

We’re not gonna do a major release just yet as I want to qualify `master` against `semantic` before we ship 1.1.

**Comment by evanrelf** [comment]
@robrix Sounds good 👍

**Pull request merged**
