### PR TITLE
ghc 9

### PR DESCRIPTION
**Pull request by robrix**
This PR supports ghc 9.0.1.

- [x] Bump bounds.
- [x] Happy new copyright year 🎉
- [x] Update CI for latest patches of previous compilers.
- [x] Update CI for ghc 9.
- [x] Ensure benchmarks compile.
- [x] :shipit:

### CODE REVIEW

**Comment by robrix** [comment]
Looks like we’re blocked on `hedgehog` (specifically its `template-haskell` dependency).

**Comment by robrix** [comment]
…but hopefully not for long! https://github.com/hedgehogqa/haskell-hedgehog/pull/392#issuecomment-775162322

**Comment by EmilGedda** [comment]
> …but hopefully not for long! [hedgehogqa/haskell-hedgehog#392 (comment)](https://github.com/hedgehogqa/haskell-hedgehog/pull/392#issuecomment-775162322)

Looking forward to playing around with `fused-effects` and GHC 9's `LinearTypes`.
It seems that [hedgehog-1.0.5](https://github.com/hedgehogqa/haskell-hedgehog/pull/417) was released two weeks ago so that blocker should be fixed now.

**Comment by patrickt** [comment]
`tasty` and `hedgehog` have been updated, but we’re still blocked on `gauge`, which is dependent on `basement` being upgraded:
https://github.com/haskell-foundation/foundation/pull/549

**Comment by Bodigrim** [comment]
It's a shameless plug, but one can switch benchmarks to [`tasty-bench`](https://github.com/Bodigrim/tasty-bench#readme), which is a drop-in replacement for `gauge` and works fine with GHC 9.0.

**Comment by patrickt** [comment]
> It's a shameless plug, but one can switch benchmarks to [`tasty-bench`](https://github.com/Bodigrim/tasty-bench#readme), which is a drop-in replacement for `gauge` and works fine with GHC 9.0.

I have no objection, as long as @robrix is okay with it. I don’t think we run the benchmarks very often, hah.

**Comment by robrix** [comment]
And after that we’ll switch back to `criterion` for ghc 9.6 and come full circle :wink:

I’m ok with that, tho IIRC I just got done switching away from `tasty` in #410 🤷🏻‍♂️

**Comment by Bodigrim** [comment]
@robrix :) 
If it's any consolation, `tasty` **core** itself is rarely a blocker for GHC upgrade. I use `tasty-bench` to benchmark `bytestring` and `text`, so keeping it compatible with future GHCs is very much on my radar.

**Comment by robrix** [comment]
I can’t explicitly approve my own PR apparently, but 👍🏻 from me.

**Pull request merged**
